### ISSUE TITLE
v2 securityDefinitions shouldn't have "scheme"

### ISSUE THREAD

**Issue by ioggstream** [LucyBot-Inc/api-spec-converter#160]
## Reproduce

- convert openapi v3 to swagger the following

```
components:
  securityScheme:
    type: http
    scheme: basic
```

## I expect

```
securityDefinitions:
  type: basic
```

## instead I get
```
securityDefinitions:
  type: basic
  scheme: basic
```
