### ISSUE TITLE
Unable to convert Open API 3 of multipart/form-data requestBody to Swagger 2

### ISSUE THREAD

**Issue by yossy-ok** [LucyBot-Inc/api-spec-converter#193]
I'm attempting to convert from Open API 3 to Swagger 2.
But I realized the converted schema has a few errors for requestBody `multipart/form-data` parameters.

My original schema is
```yaml
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                image:
                  type: string
                  format: binary
```

and converted schema is

```yaml
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: body
          required: true
          type: object
```

Actually in Swagger 2, form data parameters schema should be defined individually, like

```yaml
      parameters:
        - in: formData
          name: name
          type: string
        - in: formData
          name: image
          type: file
```

See Also:
- https://swagger.io/docs/specification/describing-request-body/file-upload
- https://swagger.io/docs/specification/2-0/file-upload

Maybe, because it doesn't convert the params schema in `multipart/form-data` case.
I think `MUTIPLART_FORM_DATA` needs same converting with `APPLICATION_X_WWW_URLENCODED` one.
https://github.com/LucyBot-Inc/api-spec-converter/blob/master/lib/converters/openapi3_to_swagger2.js#L149-L153
