### ISSUE TITLE
style attribute in response header after conversion from OpenAPI3.0 to Swagger2.0 

### ISSUE THREAD

**Issue by julianfruth** [LucyBot-Inc/api-spec-converter#272]
When i convert a OpenAPI 3.0 Swagger Document to Swagger2.0 there is the style attribute in the response headers. When i try to validate (with https://editor.swagger.io/) the converted Swagger2.0 documentation, i get a error. 

Error form editor.swagger.io:
````
Structural error at .../.../....get.responses.200.headers.MyHeaer
should NOT have additional properties
additionalProperty: style
````

Part of OpenAPI 3.0 bevore conversion: 
````yaml
        "200":
          description: Ok
          headers:
            MyHeader:
              description: test
              style: simple
              schema:
                type: string
````

Part of Swagger 2.0 after conversion:
````yaml
        '200':
          description: Ok
          headers:
            MyHeader:
              description: test
              style: simple
              type: string
````
