### ISSUE TITLE
example value changed after convertion from OpenAPI3.0 to Swagger2.0

### ISSUE THREAD

**Issue by myspec** [LucyBot-Inc/api-spec-converter#279]
```
components:
  schemas:
    Customer:
      type: object
      properties:
        birthday:
          type: string
          example: 1989-12-12
```

converted to 

```
definitions:
  Customer:
    properties:
      birthday:
        example: '1989-12-10T00:00:00.000Z'
        format: date
        type: string
```
